### ISSUE TITLE
moving from slave to master role doesn't work

### ISSUE THREAD

**Issue by fernandohonig** [rackspace-cookbooks/mysql-multi#43]
When moving a node from db_slave to db_master it doesn't work as the slave.cnf file remains in /etc/mysql/conf.d/ and the mysql starts as read-only.

**Comment by cybermerc** [comment]
This recipe (and for that matter all the -multi recipes I created) were never meant to be that smart. I will add some documentation on best practices to change a nodes state.

**Comment by cybermerc** [comment]
With the release of the new version 2.0 I have added additional documentation to address that fact that this recipe is only designed for initial setup of master and slave configurations and is not designed to address any type of fail-over situations.
