### ISSUE TITLE
bug in set_unless['mysql-multi']['bind_ip'] = best_ip_for(node) ?

### ISSUE THREAD

**Issue by nukepuppy** [rackspace-cookbooks/mysql-multi#50]
it seems even if you set this attribute that set_unless is failing? and always uses best_ip_for and that best IP may not be the 'best' IP

even when overwriting it to something like ie:
```
node.default['mysql-multi']['bind_ip'] = "127.0.0.1"
```
 127.0.0.1 it always chooses some other IP

**Comment by martinb3** [comment]
Since `set` and `set_unless` will always trump `default` attribute precedence in chef, have you tried:
```
normal['mysql-multi']['bind_ip'] = '127.0.0.1'
```
or
```
override['mysql-multi']['bind_ip'] = '127.0.0.1'
```

**Comment by nukepuppy** [comment]
trying the override definitely seemed to work - im importing the cookbook into a wrapper of an application cookbook - it is now causing other behavior but i think at least it is step in right direction.

**Comment by cybermerc** [comment]
@nukepuppy just a heads up we are about to drop a new major version of this recipe that changes the way it works drastically (also will utilize mysql community 6.x vice 5.x). It currently being polished in the multi3 branch and will be merged into master early next week.

**Comment by nukepuppy** [comment]
Oh interesting and good to know. Thanks for the heads up!  I'll start glancing at the changes and see if it's a better fit.
